name: Auto Commit

on:
  schedule:
    - cron: '*/48 * * * *'  # every 48 minutes
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make an empty commit
        run: |
          git config user.name "stayrahul-bot"
          git config user.email "rahul7926963@gmail.com"
          git commit --allow-empty -m "🤖 Auto commit"
          git push
